import "@/app/global.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
