import "@/app/global.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Product",
  description: "Generated by Product",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar product={true} />
        {children}
      </body>
    </html>
  );
}
